AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.11
      CodeUri: s3://sandol-deploy-bucket/60847926f3d6e4910d3d5df22f072833
      MemorySize: 128
      Timeout: 300
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ENV: prod
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      SamResourceId: FastApiFunction
