AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      Runtime: python3.11
      CodeUri: s3://sandol-deploy-bucket/773a22c99daca4bf37a9bcfe7c23d54f
      MemorySize: 128
      Timeout: 300
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          ENV: prod
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      SamResourceId: FastApiFunction
