service: aws-sandol

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
    pythonBin: python

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-2

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
