name: Deploy sls app

on: 
  push:
    branches:
      - main

jobs:     
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: install-python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: install serverless
      run: npm install -g serverless
    - name: serverless plugin install
      run: |
        cd aws-sandol-api
        npm install # 프로젝트 의존성 설치
        serverless plugin install -n serverless-wsgi # serverless-wsgi 플러그인 설치
    - name: severless deploy
      run: cd aws-sandol-api && serverless deploy
