name: Deploy sls app

on: 
  push:
    branches:
      - main

jobs:     
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Node.js 버전을 20.x LTS로 설정
    - name: install-python
      uses: actions/setup-python@v2 # Python 버전 3.9가 기본적으로 제공되므로 별도의 버전 명시 생략
    - name: serverless plugin install
      run: npm install -g serverless # serverless CLI 전역 설치
    - run: cd aws-sandol-api && serverless plugin install -n serverless-wsgi # serverless-wsgi 플러그인 설치
    - name: severless deploy
      run: cd aws-sandol-api && serverless deploy # serverless로 배포 명령 실행
