name: Deploy sls app

on: 
  push:
    branches:
      - feature/deploy

jobs:     
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
<<<<<<< HEAD
<<<<<<< HEAD
      - uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install serverless
        run: cd aws-sandol-api && npm install -g serverless
      - run: serverless plugin install -n serverless-wsgi
      - name: Deploy with serverless
        run: sls deploy --verbose --force
=======
=======
>>>>>>> parent of a22703c (modify cd directory path)
    - uses: actions/checkout@v3
    - name: install-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: install serverless
      run: npm i -g serverless
    - run: serverless plugin install -n serverless-wsgi
    - name: severless deploy
      run: sls deploy --verbose --force
<<<<<<< HEAD
>>>>>>> parent of a22703c (modify cd directory path)
=======
>>>>>>> parent of a22703c (modify cd directory path)

