name: Deploy to AWS

on:
  push:
    branches:
      - feature/deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r sandol/requirements.txt

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Build with SAM
        run: sam build

      - name: Package with SAM
        run: sam package --output-template-file packaged.yaml --s3-bucket sandol-deploy-bucket

      - name: Deploy with SAM
        run: sam deploy --template-file packaged.yaml --stack-name fastapi-sam-app --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset --region ap-northeast-2

